name: Live Deployment
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
    push:
        paths:
            - docs/**
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true
permissions:
    pages: write
    id-token: write
jobs:
    main:
        name: Build & Deploy
        runs-on: ubuntu-latest
        environment:
            name: GitHub Pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3
            - name: Setup Pages
              uses: actions/configure-pages@v2
            - name: Build Project
              uses: actions/jekyll-build-pages@v1
              with:
                  source: docs
            - name: Upload Artifacts
              uses: actions/upload-pages-artifact@v1
            - id: deployment
              name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v1